### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by ahankinson**
This PR does a couple of things:

1. Re-organizes the folder and app layout slightly. I was concerned that there was the potential for overlapping imports, since the 'Omas' folder contained another 'omas' folder, and the '__init__.py' handled the automatic loading. As such it was a bit obscure where and how the app was actually being run, and how I could access this app from the testing suite (see below). So I moved the `api.py` file out of the `Omas` folder and renamed it `oserver`. Then I put the code from the `__init__.py` file in `oserver.py`. Finally, I removed the `run.py` file. Now you can run the app with `python oserver.py`. The rest of the application stays in the `omas` module/folder. 

2. Added a unit testing scaffold. One of the other problems with the previous app layout was that it was unclear how to import the Flask app for unit testing. This commit adds a unit testing scaffold for the api (tests/test_api.py) that imports the Flask app and uses the built-in testing client for mocking requests to the API.

It also contains a unit test scaffold for the `MeiSlicer` class (tests/meislicer_test.py) that can be used to test the individual class without going through the API.

The test suite can by run with `python test.py` from the root directory.

### CODE REVIEW

**Comment by raffazizzi** [comment]
Hi Andrew, thanks for this!

I would prefer to not re-organize the project structure. The repository is intended to reflect EMA as a project (for better or worse) so Omas is just a component of it, at the same level of the API. I would prefer not to mix the two. Perhaps it would be smart and clearer to eventually move Omas to its own repository and only keep the API docs here.

The project structure that I've been using follows [this recommendations](http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html), which, for what I could gather, is not uncommon. 

Kepping `run.py` is useful because when flask is set up via [WSGI](http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/), it is is easy to replace `run.py` with a wsgi config.

I'm also under the impression that tests are often kept in a subfolder and run from the root directory (in this case Omas). This is what I was doing with pytest, but I after some digging around I opted for [nose](https://nose.readthedocs.org/en/latest/) instead.

I just pushed some changes to my test_musicdocinfo.py to fire up Omas as a test server and get info about a DC file. To test it, pip install nose (I added it to the requirements) and run `nosetests` from the root directory.

What do you think? Could we keep the current structure and use the nose test framework? If you agree, you could maybe adjust the tests in your pull request accordingly?

Thanks!

**Comment by ahankinson** [comment]
OK, I misunderstood what was going on. I am OK with not changing the folder structure, but perhaps making the availability of the `app` more explicit is a good idea. `from omas import omas` is not explicit and it's confusing when there is no file named "omas." It also seems like a really easy vector for a recursive or shadowed import. (I'm not a fan of "magic" happening on imports.) Maybe renaming `api` to `omasserver` so that `from omas import omasserver`? Then `omasserver.app` is available, and it's easy to see where `app` is set inside the file.

`nose` is fine too, but I don't really see the benefits for using it over the built-in `unittest` module and it's one more dependency to install. I would have to learn the nose structure, and I won't really have any time to do it before we sit down in a couple days.

**Comment by raffazizzi** [comment]
> from omas import omas is not explicit and it's confusing when there is no file named "omas." It also seems like a really easy vector for a recursive or shadowed import. (I'm not a fan of "magic" happening on imports.)

I see, yes that's a good point. `omas` (the second `omas`, that is) is another name for `app`. It may be sufficient to change it in [\_\_init\_\_.py](https://github.com/umd-mith/ema/blob/master/Omas/omas/__init__.py#L3), where Flask is initiated.

So either 
```python
app = Flask(__name__)
```
or 
```python
omasserver = Flask(__name__)
```

`nose` is able to parse `unittest` classes too, but it avoids having to have a custom testing script. 

We can talk also discuss both these issues further in person :)

**Comment by ahankinson** [comment]
The issue with doing it in `__init__.py` is that in `api.py` you then need to import the parent folder that is, itself, the flask app (e.g., "from omas import omas" or, in the proposed solution, "from omas import app"). So the app inside of the folder needs to import "up" the chain, but modules should be designed to only import "down"; a child should never have to import its parent.

**Pull request closed without merging**
